blank_issues_enabled: false
contact_links:
  - name: Contact Da Michele
    url: https://www.da-michele.com
    about: Please use our website to look up our contact details.
  - name: Da Michele Security Policy
    url: https://github.com/da-michele/.github/security/policy
    about: For security related reports please refer to our security policy.
  - name: GitHub Pages Documentation
    url: https://help.github.com/en/github/working-with-github-pages
    about: GitHub Pages official documentaion here.
  - name: GitHub Actions Documentation
    url: https://help.github.com/en/actions
    about: GitHub Actions official documentaion here.
