name: Regression Report
description: Report unexpected behavior that worked in previous versions
labels:
  - 'info: contribution-welcome'
  - 'status: triage'
assignees:
  - Vinci2020
body:

  - type: textarea
    id: description
    attributes:
      label: Describe the regression
      description: A clear and concise description of what the regression is.
    validations:
      required: true

  - type: input
    id: last-working-version
    attributes:
      label: Last working version
    validations:
      required: true

  - type: input
    id: first-broken-version
    attributes:
      label: First broken version
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior.
      value: |
        1. Step one
        2. Step two
        3. Step three
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: log-output
    attributes:
      label: Any helpful log output
      description: Please paste the results below.
      render: bash
    validations:
      required: true
